name: CI
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: '23.0'
          elixir-version: '1.10.4'
      - run: mix deps.get
      - run: echo "::add-matcher::.github/problem-matchers/exunit.json"   
      # - run: echo "::add-matcher::.github/problem-matchers/seed.json"   
      - run: mix test
